/*
 * standard public schema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 13.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using NetFighter.Converters;

namespace NetFighter.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ScanProfilesToolProfiles : IEquatable<ScanProfilesToolProfiles>
    {
        [Required]
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public int Id { get; set; }

        [Required]
        [DataMember(Name="scan_profile_id", EmitDefaultValue=true)]
        public int ScanProfileId { get; set; }

        [Required]
        [DataMember(Name="startup_profile_id", EmitDefaultValue=true)]
        public int StartupProfileId { get; set; }

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [Required]
        [DataMember(Name="order", EmitDefaultValue=true)]
        public int Order { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScanProfilesStartupProfiles {\n");
            sb.Append("  ScanProfileId: ").Append(ScanProfileId).Append("\n");
            sb.Append("  StartupProfileId: ").Append(StartupProfileId).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ScanProfilesToolProfiles)obj);
        }

        /// <summary>
        /// Returns true if ScanProfilesStartupProfiles instances are equal
        /// </summary>
        /// <param name="other">Instance of ScanProfilesStartupProfiles to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScanProfilesToolProfiles other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ScanProfileId == other.ScanProfileId ||
                    
                    ScanProfileId.Equals(other.ScanProfileId)
                ) && 
                (
                    StartupProfileId == other.StartupProfileId ||
                    
                    StartupProfileId.Equals(other.StartupProfileId)
                ) && 
                (
                    Order == other.Order ||
                    
                    Order.Equals(other.Order)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + ScanProfileId.GetHashCode();
                    
                    hashCode = hashCode * 59 + StartupProfileId.GetHashCode();
                    
                    hashCode = hashCode * 59 + Order.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ScanProfilesToolProfiles left, ScanProfilesToolProfiles right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ScanProfilesToolProfiles left, ScanProfilesToolProfiles right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
